#!/bin/bash
### BEGIN INIT INFO
# Provides:          cairo-firewall
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO

# Interface WAN monitorada
interface=enp0s8

# Não altere as linhas abaixo
VERMELHO='\033[1;31m'
VERDE='\033[1;32m'
AZUL='\033[1;36m'
AMARELO='\033[1;33m'
ROSA='\033[1;35m'
NC='\033[0m'

function startFirewall(){
    /sbin/iptables -F
    /sbin/iptables -X
    iptables -N SCANNER
    iptables -A SCANNER -m limit --limit 15/m -j LOG --log-level 6 --log-prefix "FW: port scanner: "
    iptables -A SCANNER -j DROP
    iptables -A INPUT -p tcp --tcp-flags ALL FIN,URG,PSH -i $interface -j SCANNER
    iptables -A INPUT -p tcp --tcp-flags ALL NONE -i $interface -j SCANNER
    iptables -A INPUT -p tcp --tcp-flags ALL ALL -i $interface -j SCANNER
    iptables -A INPUT -p tcp --tcp-flags ALL FIN,SYN -i $interface -j SCANNER
    iptables -A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -i $interface -j SCANNER
    iptables -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -i $interface -j SCANNER
    iptables -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -i $interface -j SCANNER
}

function stopFirewall(){
    /sbin/iptables -F
    /sbin/iptables -X
}

case "$1" in
    start )
        startFirewall
        echo; echo -e "[${VERDE} Firewall carregado ${NC}]";
        echo "Para verificar as regras use: /etc/init.d/rr-firewall status"
        ;;

    stop )
        stopFirewall
        echo; echo -e "[${VERDE} Regras de firewall removidas ${NC}]"; echo
        ;;

    restart )
        stopFirewall
        sleep 1
        startFirewall
        ;;

status )
        echo; echo -e "[${VERDE} Regras IPv4 ${NC}]"; echo
        /sbin/iptables -nL
        echo; echo -e "[${VERDE} Regras IPv6 ${NC}]"; echo
        /sbin/ip6tables -nL
        ;;

    * )
        echo "Opção inválida, use cairo-firewall start | stop | restart | status"
        ;;
esac


